const SUPABASE_URL='https://roynzxilxumfzzuezelg.supabase.co';
const ADMIN_API=`${SUPABASE_URL}/functions/v1/admin-api-v8`;
const $=id=>document.getElementById(id);
const modal=$('modal'),pw=$('pw'),err=$('err'),enter=$('enter'),secretBtn=$('secretBtn'),closeBtn=$('close');
const injectedStyle=document.createElement('style');injectedStyle.textContent=`
.photoCard{display:block!important;position:relative!important}.photoCard::before{z-index:1}.photoCard>img{z-index:0!important;transition:transform .5s}.photoCard:hover>img{transform:scale(1.025)}.photoInfo{position:absolute;z-index:3;left:12px;right:12px;bottom:12px;padding:12px 14px;background:rgba(255,253,251,.88);backdrop-filter:blur(8px);color:#665650;text-align:left;letter-spacing:0;border:1px solid rgba(255,255,255,.55)}.photoTitle{font:500 17px 'Cormorant Garamond',serif;margin-bottom:7px}.photoMeta{display:flex;flex-wrap:wrap;gap:5px 10px;color:#81716b;font-size:8px;line-height:1.5}.photoMeta span{white-space:nowrap}.photoMeta b{font-weight:500;color:#9a8279}.spotifyPreview{display:flex;align-items:center;gap:14px;margin-left:8px;min-width:0}.spotifyPreview img{width:64px;height:64px;object-fit:cover;border-radius:2px;box-shadow:0 7px 18px rgba(75,54,48,.12)}.spotifyPreview div{display:flex;flex-direction:column;gap:4px;min-width:0}.spotifyPreview strong{font:500 20px 'Cormorant Garamond',serif;color:#665650;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:260px}.spotifyPreview small{font-size:8px;letter-spacing:1px;color:#9b8982}@media(max-width:760px){.photoInfo{left:7px;right:7px;bottom:7px;padding:9px 10px}.photoTitle{font-size:15px}.photoMeta{font-size:7px;gap:3px 7px}.spotifyPreview{order:2;width:100%;margin:5px 0 0}.spotifyPreview img{width:58px;height:58px}.spotifyPreview strong{font-size:18px;max-width:220px}}
`;document.head.appendChild(injectedStyle);
if(secretBtn)secretBtn.onclick=()=>{modal.classList.remove('hidden');pw.value='';err.textContent='';setTimeout(()=>pw.focus(),50)};
if(closeBtn)closeBtn.onclick=()=>modal.classList.add('hidden');
if(modal)modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.add('hidden')});
async function login(){const password=pw.value.trim();if(!password){err.textContent='請輸入密碼。';return}enter.disabled=true;enter.textContent='Checking...';err.textContent='';try{const r=await fetch(ADMIN_API,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'login',password})});const j=await r.json();if(r.status===401&&j?.error==='invalid_password'){err.textContent='密碼不正確，再試一次。';pw.select();return}if(!r.ok){err.textContent=`登入失敗：${j?.error||`HTTP ${r.status}`}`;return}if(j?.ok&&j.token){sessionStorage.setItem('admin_token',j.token);sessionStorage.setItem('admin_expires_at',j.expires_at||'');location.replace(`admin.html?v=${Date.now()}`);return}err.textContent='登入回應不正確。'}catch(e){err.textContent='連線失敗，請稍後再試。'}finally{enter.disabled=false;enter.textContent='Enter'}}
if(enter)enter.onclick=login;if(pw)pw.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();login()}};
function text(id,v){const e=$(id);if(e)e.textContent=String(v??'').replace(/\\n/g,'\n')}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function safe(v){return String(v||'').replace(/"/g,'%22')}
function renderHero(url){const e=$('heroPhoto');if(!e||!url)return;e.style.backgroundImage=`linear-gradient(180deg,rgba(255,240,225,.04),rgba(86,64,55,.25)),url("${safe(url)}")`;e.style.backgroundSize='cover';e.style.backgroundPosition='center';e.innerHTML='<div><small>MAIN VISUAL</small></div>'}
function formatTaken(v){if(!v)return '';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('zh-TW',{year:'numeric',month:'2-digit',day:'2-digit'})}
function renderPhotos(list){const g=$('photoGrid');if(!g)return;if(!Array.isArray(list)||!list.length){g.innerHTML='<div class="photo tall">PHOTO JOURNAL<small>尚未上傳照片</small></div>';return}g.innerHTML=list.map((p,i)=>{const rows=[['相機',p.camera],['鏡頭',p.lens],['焦段',p.focal_length],['光圈',p.aperture],['ISO',p.iso],['快門',p.shutter_speed],['拍攝日期',formatTaken(p.taken_at)]].filter(x=>x[1]);const cls=i===0?'photo tall':i===3?'photo wide':i===5?'photo tall':'photo';const meta=rows.map(x=>`<span><b>${esc(x[0])}</b> ${esc(x[1])}</span>`).join('');return `<div class="${cls} photoCard"><img src="${safe(p.image_url)}" alt="${esc(p.title||'Photo')}" loading="lazy"><div class="photoInfo">${p.title?`<div class="photoTitle">${esc(p.title)}</div>`:''}<div class="photoMeta">${meta}</div></div></div>`}).join('')}
async function renderSpotify(url){const link=$('spotifyLink');if(!link)return;const clean=String(url||'').trim();link.href=clean||'#';const old=document.querySelector('.spotifyPreview');if(old)old.remove();if(!clean||!clean.includes('spotify.com'))return;try{const r=await fetch(`https://open.spotify.com/oembed?url=${encodeURIComponent(clean)}`,{cache:'no-store'});if(!r.ok)throw Error('spotify_oembed_error');const j=await r.json();const wrap=document.createElement('div');wrap.className='spotifyPreview';wrap.innerHTML=`<img src="${safe(j.thumbnail_url||'')}" alt=""><div><strong>${esc(j.title||'')}</strong><small>Spotify · ${esc(j.provider_name||'Spotify')}</small></div>`;link.parentNode.appendChild(wrap);text('musicTitle',j.title||'My little soundtrack');if($('musicDescription')&&!$('musicDescription').textContent.trim())text('musicDescription','Spotify');}catch(e){console.warn('Spotify preview unavailable',e)}}
let timer;function countdown(v){clearInterval(timer);const t=new Date(String(v).length<=10?`${v}T23:59:59`:v).getTime();if(Number.isNaN(t))return;const tick=()=>{const d=$('d'),h=$('h'),m=$('m'),s=$('s');if(!d)return;const r=Math.max(0,t-Date.now());d.textContent=Math.floor(r/86400000);h.textContent=String(Math.floor(r/3600000)%24).padStart(2,'0');m.textContent=String(Math.floor(r/60000)%60).padStart(2,'0');s.textContent=String(Math.floor(r/1000)%60).padStart(2,'0')};tick();timer=setInterval(tick,1000)}
async function loadPublic(){try{const r=await fetch(ADMIN_API,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'public'})});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'public_load_error');const c=j.content||{};text('name',c.name||'Mars');text('introText',c.intro||'喜歡用鏡頭記錄生活裡的溫柔與不經意，\n在平凡的日子裡，尋找不平凡的風景。\n希望透過照片，讓大家也能看見我眼中的世界。');if($('instagramLink'))$('instagramLink').href=c.instagram_url||'https://www.instagram.com/_oso7.m4r5/';if($('emailLink'))$('emailLink').href=c.email?`mailto:${c.email}`:'mailto:marsmars1000507@gmail.com';text('quoteText',c.quote||'有些日子沒有特別發生什麼，但回頭看，才發現它們也很值得被記住。');text('quoteAuthor',c.quote_author||'— a note to myself');text('noteTitle',c.note_title||'想說的話');text('noteText',c.note_text||'這裡可以寫給未來自己的話，也可以放一段最近很喜歡的文字。');text('noteSmall',c.note_small||'');text('musicTitle',c.music_title||'My little soundtrack');text('musicDescription',c.music_description||'最近正在播放的歌。');if($('spotifyLink'))$('spotifyLink').href=c.spotify_url||'#';text('countdownDateLabel',String(c.countdown_date||'2026-12-31').slice(0,10));if(c.hero_image)renderHero(c.hero_image);renderPhotos(j.photos||[]);await renderSpotify(c.spotify_url||'');countdown(c.countdown_date||'2026-12-31')}catch(e){console.error(e);countdown('2026-12-31')}}
loadPublic();