const SUPABASE_URL='https://roynzxilxumfzzuezelg.supabase.co';
const ADMIN_API=`${SUPABASE_URL}/functions/v1/admin-api-v8`;
const $=id=>document.getElementById(id);
const modal=$('modal'),pw=$('pw'),err=$('err'),enter=$('enter'),secretBtn=$('secretBtn'),closeBtn=$('close');
if(secretBtn)secretBtn.onclick=()=>{modal.classList.remove('hidden');pw.value='';err.textContent='';setTimeout(()=>pw.focus(),50)};
if(closeBtn)closeBtn.onclick=()=>modal.classList.add('hidden');
if(modal)modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.add('hidden')});
async function login(){const password=pw.value.trim();if(!password){err.textContent='請輸入密碼。';return}enter.disabled=true;enter.textContent='Checking...';err.textContent='';try{const r=await fetch(ADMIN_API,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'login',password})});const j=await r.json();if(r.status===401&&j?.error==='invalid_password'){err.textContent='密碼不正確，再試一次。';pw.select();return}if(!r.ok){err.textContent=`登入失敗：${j?.error||`HTTP ${r.status}`}`;return}if(j?.ok&&j.token){sessionStorage.setItem('admin_token',j.token);sessionStorage.setItem('admin_expires_at',j.expires_at||'');location.replace(`admin.html?v=${Date.now()}`);return}err.textContent='登入回應不正確。'}catch(e){err.textContent='連線失敗，請稍後再試。'}finally{enter.disabled=false;enter.textContent='Enter'}}
if(enter)enter.onclick=login;if(pw)pw.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();login()}};
function text(id,v){const e=$(id);if(e)e.textContent=String(v??'').replace(/\\n/g,'\n')}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function safe(v){return String(v||'').replace(/"/g,'%22')}
function renderHero(url){const e=$('heroPhoto');if(!e||!url)return;e.style.backgroundImage=`linear-gradient(180deg,rgba(255,240,225,.04),rgba(86,64,55,.25)),url("${safe(url)}")`;e.style.backgroundSize='cover';e.style.backgroundPosition='center';e.innerHTML='<div><small>MAIN VISUAL</small></div>'}
function renderPhotos(list){const g=$('photoGrid');if(!g||!Array.isArray(list)||!list.length)return;g.innerHTML=list.map((p,i)=>{const meta=[p.camera,p.lens,p.focal_length,p.aperture,p.iso,p.shutter_speed,p.taken_at].filter(Boolean).join(' · ');const cls=i===0?'photo tall':i===3?'photo wide':i===5?'photo tall':'photo';return `<div class="${cls}"><img src="${safe(p.image_url)}" alt="${esc(p.title||'PHOTO')}" loading="lazy" style="width:100%;height:100%;object-fit:cover;position:absolute;inset:0"><div style="position:relative;z-index:2;padding:11px;background:rgba(255,253,251,.84);max-width:90%;color:#665650;font-size:10px;letter-spacing:1px">${esc(p.title||`PHOTO ${String(i+1).padStart(2,'0')}`)}${meta?`<small style="display:block;margin-top:5px;font-size:8px;letter-spacing:.2px">${esc(meta)}</small>`:''}</div></div>`}).join('')}
let timer;function countdown(v){clearInterval(timer);const t=new Date(String(v).length<=10?`${v}T23:59:59`:v).getTime();if(Number.isNaN(t))return;const tick=()=>{const d=$('d'),h=$('h'),m=$('m'),s=$('s');if(!d)return;const r=Math.max(0,t-Date.now());d.textContent=Math.floor(r/86400000);h.textContent=String(Math.floor(r/3600000)%24).padStart(2,'0');m.textContent=String(Math.floor(r/60000)%60).padStart(2,'0');s.textContent=String(Math.floor(r/1000)%60).padStart(2,'0')};tick();timer=setInterval(tick,1000)}
async function loadPublic(){try{const r=await fetch(ADMIN_API,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'public'})});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'public_load_error');const c=j.content||{};text('name',c.name||'Mars');text('introText',c.intro||'喜歡用鏡頭記錄生活裡的溫柔與不經意，\n在平凡的日子裡，尋找不平凡的風景。\n希望透過照片，讓大家也能看見我眼中的世界。');if($('instagramLink'))$('instagramLink').href=c.instagram_url||'https://www.instagram.com/_oso7.m4r5/';if($('emailLink'))$('emailLink').href=c.email?`mailto:${c.email}`:'mailto:marsmars1000507@gmail.com';text('quoteText',c.quote||'有些日子沒有特別發生什麼，但回頭看，才發現它們也很值得被記住。');text('quoteAuthor',c.quote_author||'— a note to myself');text('noteTitle',c.note_title||'想說的話');text('noteText',c.note_text||'這裡可以寫給未來自己的話，也可以放一段最近很喜歡的文字。');text('noteSmall',c.note_small||'');text('musicTitle',c.music_title||'My little soundtrack');text('musicDescription',c.music_description||'最近正在播放的歌。');if($('spotifyLink'))$('spotifyLink').href=c.spotify_url||'#';text('countdownDateLabel',String(c.countdown_date||'2026-12-31').slice(0,10));if(c.hero_image)renderHero(c.hero_image);renderPhotos(j.photos||[]);countdown(c.countdown_date||'2026-12-31')}catch(e){console.error(e);countdown('2026-12-31')}}
loadPublic();