const SUPABASE_URL='https://roynzxilxumfzzuezelg.supabase.co';
const ADMIN_API=`${SUPABASE_URL}/functions/v1/admin-api-v8`;
const $=id=>document.getElementById(id);
const modal=$('modal'),pw=$('pw'),err=$('err'),enter=$('enter'),secretBtn=$('secretBtn'),closeBtn=$('close');
const injectedStyle=document.createElement('style');injectedStyle.textContent=`
.photoCard{display:flex!important;flex-direction:column!important;position:relative!important;height:auto!important;min-height:0!important;overflow:visible!important;background:transparent!important}.photoCard>img{position:relative!important;z-index:0!important;width:100%!important;height:auto!important;aspect-ratio:auto!important;object-fit:contain!important;display:block!important;transition:transform .5s;border-radius:2px}.photoCard:hover>img{transform:scale(1.01)}.photoInfo{position:static!important;width:100%!important;margin:0!important;padding:11px 4px 2px!important;background:transparent!important;backdrop-filter:none!important;color:#665650;text-align:left;letter-spacing:0;border:0!important;box-shadow:none!important}.photoTitle{font:500 17px 'Cormorant Garamond',serif;margin-bottom:6px}.photoMeta{display:flex;flex-wrap:wrap;gap:4px 9px;color:#81716b;font-size:8px;line-height:1.45}.photoMeta span{white-space:nowrap}.photoMeta b{font-weight:500;color:#9a8279}.grid{grid-auto-rows:auto!important;align-items:start!important}.spotifyPreview{display:flex;align-items:center;gap:17px;flex:1;min-width:0;margin:0}.spotifyPreview img{width:76px;height:76px;flex:none;object-fit:cover;border-radius:4px;box-shadow:0 9px 22px rgba(75,54,48,.13)}.spotifyPreview .spotifyInfo{display:flex;flex-direction:column;gap:5px;min-width:10em;flex:1}.spotifyPreview strong{font:500 25px/1.15 'Cormorant Garamond',serif;color:#665650;white-space:normal;overflow:visible;text-overflow:clip;max-width:none;min-width:10em;word-break:break-word;overflow-wrap:anywhere}.spotifyPreview small{font-size:8px;letter-spacing:1.8px;color:#9b8982}.spotifyPlay{margin-left:auto;flex:none;padding:10px 17px;border:1px solid #ded3cd;color:#77645d;text-decoration:none;font-size:9px;letter-spacing:1.2px;transition:.3s}.spotifyPlay:hover{background:#77645d;color:#fff}.music.hasSpotify .musicText{display:none}.music.hasSpotify #spotifyLink{display:none!important}@media(max-width:760px){.photoInfo{padding:8px 2px 1px!important}.photoTitle{font-size:14px}.photoMeta{font-size:7px;gap:3px 6px}.grid{grid-auto-rows:auto!important}.spotifyPreview{gap:11px;align-items:center;flex-wrap:wrap}.spotifyPreview img{width:60px;height:60px}.spotifyPreview .spotifyInfo{min-width:10em;flex:1}.spotifyPreview strong{font-size:18px;line-height:1.2;min-width:10em}.spotifyPlay{margin-left:auto;padding:8px 10px;font-size:8px}.music.hasSpotify{padding:18px}.music.hasSpotify .spotifyPreview{width:100%}}
`;document.head.appendChild(injectedStyle);
if(secretBtn)secretBtn.onclick=()=>{modal.classList.remove('hidden');pw.value='';err.textContent='';setTimeout(()=>pw.focus(),50)};
if(closeBtn)closeBtn.onclick=()=>modal.classList.add('hidden');
if(modal)modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.add('hidden')});
async function login(){const password=pw.value.trim();if(!password){err.textContent='請輸入密碼。';return}enter.disabled=true;enter.textContent='Checking...';err.textContent='';try{const r=await fetch(ADMIN_API,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'login',password})});const j=await r.json();if(r.status===401&&j?.error==='invalid_password'){err.textContent='密碼不正確，再試一次。';pw.select();return}if(!r.ok){err.textContent=`登入失敗：${j?.error||`HTTP ${r.status}`}`;return}if(j?.ok&&j.token){sessionStorage.setItem('admin_token',j.token);sessionStorage.setItem('admin_expires_at',j.expires_at||'');location.replace(`admin.html?v=${Date.now()}`);return}err.textContent='登入回應不正確。'}catch(e){err.textContent='連線失敗，請稍後再試。'}finally{enter.disabled=false;enter.textContent='Enter'}}
if(enter)enter.onclick=login;if(pw)pw.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();login()}};
function text(id,v){const e=$(id);if(e)e.textContent=String(v??'').replace(/\\n/g,'\n')}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function safe(v){return String(v||'').replace(/"/g,'%22')}
function renderHero(url){const e=$('heroPhoto');if(!e||!url)return;e.style.backgroundImage=`linear-gradient(180deg,rgba(255,240,225,.04),rgba(86,64,55,.25)),url("${safe(url)}")`;e.style.backgroundSize='cover';e.style.backgroundPosition='center';e.innerHTML='<div><small>MAIN VISUAL</small></div>'}
function formatTaken(v){if(!v)return '';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('zh-TW',{year:'numeric',month:'2-digit',day:'2-digit'})}
function renderPhotos(list){const g=$('photoGrid');if(!g)return;if(!Array.isArray(list)||!list.length){g.innerHTML='<div class="photo tall">PHOTO JOURNAL<small>尚未上傳照片</small></div>';return}g.innerHTML=list.map((p,i)=>{const rows=[['相機',p.camera],['鏡頭',p.lens],['焦段',p.focal_length],['光圈',p.aperture],['ISO',p.iso],['快門',p.shutter_speed],['拍攝日期',formatTaken(p.taken_at)]].filter(x=>x[1]);const cls='photo';const meta=rows.map(x=>`<span><b>${esc(x[0])}</b> ${esc(x[1])}</span>`).join('');return `<div class="${cls} photoCard"><img src="${safe(p.image_url)}" alt="${esc(p.title||'Photo')}" loading="lazy"><div class="photoInfo">${p.title?`<div class="photoTitle">${esc(p.title)}</div>`:''}<div class="photoMeta">${meta}</div></div></div>`}).join('')}
async function renderSpotify(url){const link=$('spotifyLink');if(!link)return;const clean=String(url||'').trim();link.href=clean||'#';const old=document.querySelector('.spotifyPreview');if(old)old.remove();const music=document.querySelector('.music');if(music)music.classList.remove('hasSpotify');if(!clean||!clean.includes('spotify.com'))return;try{const r=await fetch(`https://open.spotify.com/oembed?url=${encodeURIComponent(clean)}`,{cache:'no-store'});if(!r.ok)throw Error('spotify_oembed_error');const j=await r.json();const wrap=document.createElement('div');wrap.className='spotifyPreview';wrap.innerHTML=`<img src="${safe(j.thumbnail_url||'')}" alt=""><div class="spotifyInfo"><small>NOW PLAYING · SPOTIFY</small><strong>${esc(j.title||'')}</strong></div><a class="spotifyPlay" href="${safe(clean)}" target="_blank" rel="noopener">OPEN ↗</a>`;if(music){music.classList.add('hasSpotify');const textBox=music.querySelector('#musicTitle')?.parentElement;if(textBox)textBox.replaceWith(wrap);else music.prepend(wrap)}else link.parentNode.appendChild(wrap);text('musicTitle',j.title||'My little soundtrack');if($('musicDescription')&&!$('musicDescription').textContent.trim())text('musicDescription','Spotify');}catch(e){console.warn('Spotify preview unavailable',e)}}
let timer;function countdown(v){clearInterval(timer);const t=new Date(String(v).length<=10?`${v}T23:59:59`:v).getTime();if(Number.isNaN(t))return;const tick=()=>{const d=$('d'),h=$('h'),m=$('m'),s=$('s');if(!d)return;const r=Math.max(0,t-Date.now());d.textContent=Math.floor(r/86400000);h.textContent=String(Math.floor(r/3600000)%24).padStart(2,'0');m.textContent=String(Math.floor(r/60000)%60).padStart(2,'0');s.textContent=String(Math.floor(r/1000)%60).padStart(2,'0')};tick();timer=setInterval(tick,1000)}
async function loadPublic(){try{const r=await fetch(ADMIN_API,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'public'})});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'public_load_error');const c=j.content||{};text('name',c.name||'Mars');text('introText',c.intro||'喜歡用鏡頭記錄生活裡的溫柔與不經意，\n在平凡的日子裡，尋找不平凡的風景。\n希望透過照片，讓大家也能看見我眼中的世界。');if($('instagramLink')){$('instagramLink').href=c.instagram_url||'https://www.instagram.com/_oso7.m4r5/';$('instagramLink').textContent='Instagram'}if($('emailLink')){$('emailLink').href=c.email?`mailto:${c.email}`:'mailto:marsmars1000507@gmail.com';$('emailLink').textContent='Email'}text('quoteText',c.quote||'有些日子沒有特別發生什麼，但回頭看，才發現它們也很值得被記住。');text('quoteAuthor',c.quote_author||'— a note to myself');text('noteTitle',c.note_title||'想說的話');text('noteText',c.note_text||'這裡可以寫給未來自己的話，也可以放一段最近很喜歡的文字。');text('noteSmall',c.note_small||'');text('musicTitle',c.music_title||'My little soundtrack');text('musicDescription',c.music_description||'最近正在播放的歌。');if($('spotifyLink'))$('spotifyLink').href=c.spotify_url||'#';text('countdownDateLabel',String(c.countdown_date||'2026-12-31').slice(0,10));if(c.hero_image)renderHero(c.hero_image);renderPhotos(j.photos||[]);await renderSpotify(c.spotify_url||'');countdown(c.countdown_date||'2026-12-31')}catch(e){console.error(e);countdown('2026-12-31')}}
loadPublic();